Running job on Hoffman2 with Job ID: 7790085
Loaded Modules:
Currently Loaded Modulefiles:
 1) python/3.9.6(default)   2) anaconda3/2023.03  

Key:
(symbolic-version)  
Python 3.9.6 and Anaconda3 2023.03 modules loaded

Apptainer loaded successfully!
apptainer version 1.2.2
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    underlay of /etc/localtime required more than 50 (88) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (379) bind mounts

INFO:    instance started successfully
Started Apptainer instance: myollama
tangai   204667 25.0  0.0  25180  1684 ?        R    03:43   0:00 /bin/squashfuse_ll -f -o offset=40960 /proc/self/fd/3 /u/local/apps/apptainer/1.2.2/var/apptainer/mnt/session/rootfs
tangai   204688  0.0  0.0   9100   684 ?        S    03:43   0:00 grep apptainer
INSTANCE NAME    PID       IP    IMAGE
myollama         204654          /u/local/apps/apptainer/H2_containers/h2-ollama.sif

Conda environment activated successfully

Using Python from: /u/project/tpresner/shared/mypython/bin/python
Python 3.9.21

Flask server started with PID 204721

Running normally (not inside qsub).
 * Serving Flask app 'server'
 * Debug mode: off
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.16.104.239:5000
[33mPress CTRL+C to quit[0m
python: can't open file '/u/project/tpresner/shared/qsub/prod/qsub_client.py': [Errno 2] No such file or directory
Client script failed to execute. Check Flask server logs.
Stopping Flask server with PID 204721
Flask server stopped successfully.
INFO:    Stopping myollama instance of /u/local/apps/apptainer/H2_containers/h2-ollama.sif (PID=204654)
myollama apptainer instance stopped.
