Running job on Hoffman2 with Job ID: 7790077
Loaded Modules:
Currently Loaded Modulefiles:
 1) python/3.9.6(default)   2) anaconda3/2023.03  

Key:
(symbolic-version)  
Python 3.9.6 and Anaconda3 2023.03 modules loaded

Apptainer loaded successfully!
apptainer version 1.2.2
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    underlay of /etc/localtime required more than 50 (88) bind mounts
INFO:    underlay of /usr/bin/nvidia-smi required more than 50 (379) bind mounts

INFO:    instance started successfully
Started Apptainer instance: myollama
tangai   201126  0.0  0.0  25232  1856 ?        S    03:14   0:00 /bin/squashfuse_ll -f -o offset=40960 /proc/self/fd/3 /u/local/apps/apptainer/1.2.2/var/apptainer/mnt/session/rootfs
tangai   201148  0.0  0.0   9100   688 ?        S    03:14   0:00 grep apptainer
INSTANCE NAME    PID       IP    IMAGE
myollama         201113          /u/local/apps/apptainer/H2_containers/h2-ollama.sif

Conda environment activated successfully

Using Python from: /u/project/tpresner/shared/mypython/bin/python
Python 3.9.21

Flask server started with PID 201183

python: can't open file '/u/project/tpresner/shared/qsub/practice/qsub_server.py': [Errno 2] No such file or directory
Flask server failed to start. Exiting.
